# Generated by Django 5.2.4 on 2025-08-05 09:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tag_id', models.CharField(max_length=50, unique=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TemperatureReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('chick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='monitor.chick')),
            ],
        ),
    ]
