# Generated by Django 5.2.4 on 2025-08-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_feveralert'),
    ]

    operations = [
        migrations.AddField(
            model_name='feveralert',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
