# Generated by Django 5.2.4 on 2025-08-05 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_feveralert_resolved_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feveralert',
            name='chick',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitor.chick'),
        ),
    ]
